# Generated by Django 4.2.14 on 2024-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField(help_text='in US Dollars $')),
                ('genre', models.CharField(choices=[('educational', 'Educational'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('romantic', 'Romantic'), ('classic', 'Classic'), ('comic', 'Comic')], default='cl', max_length=12)),
                ('book_type', models.CharField(choices=[('hardcover', 'Hard Cover'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hc', max_length=12)),
            ],
        ),
    ]
