# Generated by Django 4.2.14 on 2024-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('educational', 'Educational'), ('classic', 'Classic'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romantic', 'Romantic'), ('comic', 'Comic')], default='cl', max_length=12),
        ),
    ]
