# Generated by Django 4.2.14 on 2024-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='unknown', max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('educational', 'Educational'), ('horror', 'Horror'), ('comic', 'Comic'), ('classic', 'Classic'), ('fantasy', 'Fantasy')], default='cl', max_length=12),
        ),
    ]
