# Generated by Django 4.2.14 on 2024-07-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author_name_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hard Cover'), ('audiobook', 'Audiobook'), ('ebook', 'E-Book')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('classic', 'Classic'), ('comic', 'Comic'), ('educational', 'Educational')], default='cl', max_length=12),
        ),
    ]
