# Generated by Django 4.2.14 on 2024-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_pic_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('audiobook', 'Audiobook'), ('hardcover', 'Hard Cover'), ('ebook', 'E-Book')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('romantic', 'Romantic'), ('horror', 'Horror'), ('comic', 'Comic'), ('classic', 'Classic'), ('educational', 'Educational')], default='cl', max_length=12),
        ),
    ]
