# Generated by Django 4.2.14 on 2024-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_type_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('ebook', 'E-Book'), ('audiobook', 'Audiobook'), ('hardcover', 'Hard Cover')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romantic', 'Romantic'), ('educational', 'Educational'), ('comic', 'Comic'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('classic', 'Classic')], default='cl', max_length=12),
        ),
    ]
